apiVersion: v1
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: demo-jenkins-x-spring-act
version: 0.1.0-SNAPSHOT
